COVID-19-Data-Tracker
ZeenatLawal/COVID-19-Data-Tracker pull request #6
Opened 2021-10-14 14:35 UTC by ZeenatLawal

In this project, I:

- Created the React App.
- Selected the MMediaGroup Covid-19 API for Data
- Installed basic dependencies (React-Redux, Redux Logger and React Router).
- Created routes and navigations for the app
- Created the directory for all Redux state slice files.
- Created routes and view components for the Home and Details page.
- Fetched data from the API when the application starts.
- Dispatched an action to store the selected data in the Redux store.
- Used `useSelector()`, Redux Hook, to select the state slices and render countries and country details in corresponding routes.
- Implemented the Filter for filtering the number of confirmed cases.
- Write unit tests with Jest and React Testing Library
- Styled the application using plain CSS and React Bootstrap. 
- Integrated linters.

> [Live Demo](https://covid-19-data-tracker-zee.netlify.app/)
> [Video Demo](https://www.loom.com/share/15a4f97a8fe6484ab84c3268b6e38f60)

2021-10-14 19:56 UTC, oloomoses requested changes
Hi @ZeenatLawal, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-14 19:56 UTC, oloomoses commented on src/components/Card.js
> +/* eslint-disable react/prop-types */
- [ ] The linters are there to enforce code quality and should not be disabled. Kindly enable the linters and fix the issues raised.  In this case, check that the props are validated and the dot-notation issue fixed.

2021-10-14 19:56 UTC, oloomoses commented on src/components/Navbar.js
> +import React from 'react';
- [ ] The linters are there to enforce code quality and should not be disabled. Kindly enable the linters and fix the issues raised.  In this case, check that the props are validated.

2021-10-14 19:56 UTC, oloomoses commented on src/components/TotalCard.js
> +import React from 'react';
- [ ] The linters are there to enforce code quality and should not be disabled. Kindly enable the linters and fix the issues raised.  In this case, check that the props are validated.

2021-10-14 19:56 UTC, oloomoses commented on src/pages/Home.js
> +import React from 'react';
- [ ] The linters are there to enforce code quality and should not be disabled. Kindly enable the linters and fix the issues raised.  In this case, check that the dot-notation is fixed.

2021-10-14 19:56 UTC, oloomoses commented on src/redux/countries/countries.js
> +/* eslint-disable max-len */
- [ ] The linters are there to enforce code quality and should not be disabled. Kindly enable the linters and fix the issues raised.  Kindly fix the dot-notation and max-len issue.

2021-10-14 19:56 UTC, oloomoses commented on src/tests/Home.test.js
> +import renderer from 'react-test-renderer';
- [ ] The linters are there to enforce code quality and should not be disabled. Kindly enable the linters and fix the issues raised.  In this case, fix the no-unused-expressions issue.

2021-10-14 19:56 UTC, oloomoses commented on src/redux/configureStore.js
> +);
- [ ] Please do not log redux data on the browser console as it may cause site security issues. Kindly clear the logged data displayed on the browser console.

2021-10-15 05:46 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-10-15 07:34 UTC, merged